### ISSUE TITLE
UKELD calculation error

### ISSUE THREAD

**Issue by drsjg** [SurgicalInformatics/liverapp#1]
Hi,

We've found an issue with the UKELD calculator.

A patient has a bilirubin of 8. Since slider will not accept bili values <10, her UKELD is calculated as 49 rather than the correct value of 48. To reproduce -  INR 1.0, bilirubin 8, Na 136, creat 112.  

This is an edge case and unlikely to significantly affect decision-making for individual patients, but could slider be modified to allow lower bilirubin values to be entered?

Great web app.

Thanks.

**Comment by ewenharrison** [comment]
Thanks, yes this was fixed.
